name: auto commit and push to master branch

on:
  schedule:
    - cron: "50 17 * * *" #UTC每天0点

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Set up Git
        run: |
          git config --global user.name 'GaoYang'
          git config --global user.email 'GaoYangBenYang@outlook.com'
      
      - name: update files
        run: |
          echo "$(date)" >> README.md
     
      - name: Commit files
        run: |
          git add .
          git commit -m "Auto commit at $(date +"%Y-%m-%d %T")"
          
      - name: Push changes
        run: |
          git push origin master
