name: auto commit and push to master branch

on:
  schedule:
    - cron: "20 17 * * *" #UTC每天0点
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up Git
        run: |
          git config --global user.name 'GaoYang'
          git config --global user.email 'GaoYangBenYang@outlook.com'
          
      - name: Commit files
        run: |
          git add .
          git commit -m "Auto commit at $(date +"%Y-%m-%d %T")"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
